Setup CI/CD Cleanup Requirements and Lint

diff --git a/.github/workflows/django.yml b/.github/workflows/django.yml
--- a/.github/workflows/django.yml
+++ b/.github/workflows/django.yml
@@ -1,10 +1,10 @@
-name: Django CI
+name: Cloud Bloom Build
 
 on:
   push:
-    branches: [ "main" ]
+    branches: [ main ]
   pull_request:
-    branches: [ "main" ]
+    branches: [ main ]
 
 jobs:
   build:
@@ -13,18 +13,49 @@ jobs:
     strategy:
       max-parallel: 4
       matrix:
-        python-version: [3.7, 3.8, 3.9]
+        python-version: [3.8,3.9,3.10]
 
     steps:
-    - uses: actions/checkout@v3
+    - uses: actions/checkout@v2
     - name: Set up Python ${{ matrix.python-version }}
-      uses: actions/setup-python@v3
+      uses: actions/setup-python@v1
       with:
         python-version: ${{ matrix.python-version }}
     - name: Install Dependencies
+      if: success() || failure()
       run: |
         python -m pip install --upgrade pip
-        pip install -r requirements.txt
-    - name: Run Tests
+        pip install -r ./requirements.txt
+        - name: Lint with flake8
       run: |
-        python manage.py test
+        pip install flake8
+        # stop the build if there are Python syntax errors or undefined names
+        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
+        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
+        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
+    - name: Lint with pylint
+      run: |
+        pip install pylint
+        pylint .
+    - name: Lint with black
+      run: |
+        pip install black
+        black .
+    - name: Lint with isort
+      run: |
+        pip install isort
+        isort .
+    - name: Lint with pycodestyle
+      run: |
+        pip install pycodestyle
+        pycodestyle .
+    - name: Lint with mypy
+      run: |
+        pip install mypy
+        mypy .
+    # - name: Run Tests'
+    #   if: success() || failure()
+    #   env:
+    #     SECRET_KEY: ''
+    #   run: |
+    #     python manage.py test
